# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10c3c218eaa3ce2db22aa0cdbe4551d4324fdcec1c9d359953a5675bf8832d87dacb5717e0129bd1c55dce8f87aef9cb054797e91263b83e2402a8d172282698

test:
  secret_key_base: 542e64299c7f638263e22480ed157f3402b64ef9d2b2161dd3bf1560c2117c2d5ce9dd346365ede45801e38d28a4cc58b7b32a8a60d3a6cfd44c89edef6cc1b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
